# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6c46dfaca65433ed69ca74be09da8c62a54db176d75635a25250666002b20915b747345a663dfb2d6851863f28c0fdc65b04565f2b68bfa20763825fd038b53

test:
  secret_key_base: 4ce082620a4732fdc0081a17b1330f521c5f6389e274b5c0f95cb78be2916fc1e13dc99146f487514187574e3225cb58f1c4b484658a549fab885142a3169774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
